# Generated by Django 4.2.4 on 2023-08-17 01:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={},
        ),
    ]
