# Generated by Django 4.2.4 on 2023-08-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0004_veiculo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="veiculo",
            options={},
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="acessorios",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="descricao",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="garagem.categoria",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="veiculo",
            name="marca",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="garagem.marca",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="ano",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
