# Generated by Django 4.2.4 on 2023-08-16 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0005_alter_veiculo_options_remove_veiculo_acessorios_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"verbose_name": "acessório"},
        ),
        migrations.AlterModelOptions(
            name="veiculo",
            options={"verbose_name": "Veículo"},
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="marca",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="descricao",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelos",
                        to="garagem.categoria",
                    ),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelos",
                        to="garagem.marca",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Modelos",
            },
        ),
        migrations.AddField(
            model_name="veiculo",
            name="modelo",
            field=models.ForeignKey(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="garagem.modelo",
            ),
        ),
    ]
