# Generated by Django 4.2.4 on 2023-08-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0006_alter_acessorio_options_alter_veiculo_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="acessorios",
            field=models.ManyToManyField(
                related_name="veiculos", to="garagem.acessorio"
            ),
        ),
    ]
