# Generated by Django 4.2.4 on 2023-08-17 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0007_veiculo_acessorios"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={},
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name": "Acessório"},
        ),
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name_plural": "Cores"},
        ),
        migrations.RemoveField(
            model_name="veiculo",
            name="acessorios",
        ),
    ]
